name: GhPage

on:
  push:
    branches:
      - master

jobs:
  build_dart_packages:
    runs-on: ubuntu-latest

    container:
      image: google/dart:${{ matrix.version }}

    strategy:
      matrix:
        version: ["latest"]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pub get

      - name: Analyze
        run: dartanalyzer --fatal-infos --fatal-warnings .

      - name: Install peanut
        run: pub global activate peanut

      - name: Commit files
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Penut
        run: pub global run peanut

      - name: Checkout gh-pages
        run: git checkout gh-pages

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
