name: GhPage

on:
  push:
    branches:
      - master

jobs:
  build_dart_packages:
    runs-on: ubuntu-latest

    container:
      image: google/dart:${{ matrix.version }}

    strategy:
      matrix:
        version: ["latest"]

    steps:
      - uses: actions/checkout@v2

      - name: Install peanut
        run: pub global activate peanut

      - name: Install dependencies
        run: pub get

      - name: Analyze
        run: dartanalyzer --fatal-infos --fatal-warnings .

      - name: Setup GH user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Build web app
        run: pub global run peanut

      - name: Checkout gh-pages
        run: git checkout gh-pages

      - name: Deploy gh-page
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: .